config/routes.rb
Rails.application.routes.draw do

  root to: "options#index"

  get "options" => "options#index"
  post "randomize" => "randomize#index"
  get "randomize/:pokemon" => "randomize#show"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController

  def index
  end
  
end

app/controllers/randomize_controller.rb
class RandomizeController < ApplicationController

  def index
    @players = params[:people].to_i if params[:people]
    @pokemon = params[:pokemon].to_i if params[:pokemon]

    playerset
    pokemonset
  end

  def show
    render json: {
      pokemon: ActionController::Base.helpers.asset_path("pokemon/#{params[:pokemon]}")
    }
  end

  private

  def playerset
    @players ||= 4
  end

  def pokemonset
    @pokemon ||= 3
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/randomize_helper.rb
module RandomizeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoulettePokemon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/options/index.html.erb
<div class="options">
  <%= form_tag randomize_path, method: "POST" do %>
    
    How many players are getting randomized:
    <div>
      <%= label_tag :"1" %>:
      <%= radio_button_tag :people, "1" %>
      <%= label_tag :"2" %>:
      <%= radio_button_tag :people, "2" %>
      <%= label_tag :"3" %>:
      <%= radio_button_tag :people, "3" %>
      <%= label_tag :"4" %>:
      <%= radio_button_tag :people, "4" %>
    </div>
    
    How many Pokemon does each player want:
    <div>
      <%= label_tag :"1" %>:
      <%= radio_button_tag :pokemon, "1" %>
      <%= label_tag :"2" %>:
      <%= radio_button_tag :pokemon, "2" %>
      <%= label_tag :"3" %>:
      <%= radio_button_tag :pokemon, "3" %>
      <%= label_tag :"4" %>:
      <%= radio_button_tag :pokemon, "4" %>
      <%= label_tag :"5" %>:
      <%= radio_button_tag :pokemon, "5" %>
      <%= label_tag :"6" %>:
      <%= radio_button_tag :pokemon, "6" %>
    </div>

    <%= submit_tag "Randomize" %>

  <% end %>
</div>

app/views/randomize/index.html.erb
<% @players.times do | player_num |%>

  <div class="trainer" id="player_<%= player_num + 1 %>">

    <div class="name">Trainer <%= player_num + 1 %>:</div>

    <div class="pokecontainer">

      <% @pokemon.times do | poke_num | %>

        <div class="pokemon" id="pokemon_<%= poke_num + 1 %>">
          <div class="image" id="<%= player_num %><%= poke_num %>"></div>
          <div class="button">
            <button class="roll" id="<%= player_num %><%= poke_num %>">Roll</button>
          </div>
        </div>

      <% end %>

    </div>
  </div>

<% end %>